### ISSUE TITLE
unable to find batch

### ISSUE THREAD

**Issue by Premkanna22** [nils-soderman/vscode-batch-runner#15] opened 2023-11-18 18:30 UTC
not existing

**Comment by nils-soderman** [comment] 2023-11-18 20:13
Hi, could you please provide more information or perhaps a screenshot of the issue?
Where are you getting this _"unable to find batch"_ message? and what do you click/run to trigger it?

**Comment by nils-soderman** [comment] 2023-12-02 10:28
Due to a lack of information I'm going to close this issue for now, feel free to re-open it with more information on how to reproduce this.

**Closed by nils-soderman** 2023-12-02 10:28 UTC
